### ISSUE TITLE
【下次处理】【JOB】【严重】报错信息的准确性优化，

### ISSUE THREAD

**Issue by XiaoE0203** [Tencent/bk-job#1330]
![image](https://user-images.githubusercontent.com/54015094/191256766-ab0b1e65-1cd9-42de-a21a-715b91dc2c0f.png)

**Comment by nekzhang** [comment]
用户查找不存在时，如果是事务（即，全员发送失败或成功）则：
`ZH`: 发送通知失败！查询不到该用户[{{username}}]。
`EN`: Failed to send message! The user(s) [{{username}}] could not be found.

用户查找不存在时，如果非事务（即，能拉取到的人员都正常发送、拉不到的人员不发）则：
`ZH`: 因查询不到数据，用户[{{username}}]消息发送失败！
`EN`: Failed to send message to user(s) [{{username}}], because they could not be found!

**Comment by nekzhang** [comment]
已确认该issue属于消息发送服务的报错信息优化项，JOB不影响。
